# Created by Josue Lopez July 03, 2020

# This workflow will checkout code on the branch with an open pull reuqest
# It will run a static linter with a single version of Python 3.6
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint API

on:
  pull_request:
     branches: [ master, release ]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Set up Python 3.6
        uses: actions/setup-python@v1
        with: 
          python-version: 3.6
      - 
        name: Install Pylint
        run: |
            python -m pip install --upgrade pip
            pip install pylint==2.5.3
      -
        name: Get base commit for PRs
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "base_sha=$(git rev-parse origin/${{ github.base_ref }})" >> $GITHUB_ENV 
          echo "Merging ${{ github.sha }} into ${{ github.base_ref }}"
      - 
        name: Get the changed files
        run: |
          printf "Files Changed: $(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})\n"
          
          changed_files=$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})
          
          printf "${changed_files}\n"
          # printf "${changed_files}" >> $GITHUB_ENV  HOW to store env???
          ./src/scripts/lint.sh ${changed_files}

      - 
        name: Lint and Rate Code
        run: |
            # To understand pylint arguments visit link below
            # https://docs.pylint.org/en/1.6.0/features.html
            
            echo "Global Evaluation of Python Code is currently: "

            pylint --exit-zero --jobs=0 ./src --score=y --disable=E1101 \
              --msg-template="{msg_id}: {category}: {path} {line}:{column} {msg}" \
              | awk '$0 ~ /Your code/ || $0 ~ /Global/ {print}'
            
            
            
            
  
