# Created by Josue Lopez Aug 11, 2020
name: Update Release Tag with Auto Semantic Versioning

on:
  push:
    branches: [ master ]

jobs:
  create-new-tag-version:
    name: create-new-tag-version

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Enabling NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get -y -qq update
    - run: sudo apt-get install python-pip python-dev build-essential
    - run: sudo pip install --upgrade pip
    - run: sudo pip install --upgrade setuptools

    - name: Install npm bump dependencies modules
    - run: npm install

    - name: npm run bump
    - run: npm run bump


    - name: push commits and release tags to GitHub
    - run: git push --follow-tags origin ${GITHUB_REF##*/}

    # - name: Notify job status on Slack
    # - uses: sonots/slack-notice-action@v3
    #   with:
    #     status: ${{ job.status }}
    #     title: API Deployment
    #     text: Attempted Deployment from Branch ${{ github.ref }} and status is ${{ job.status }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required, but GitHub should automatically supply
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    #   if: always() # Pick up events even if the job fails or is canceled.
